from typing import Any

from _unsafe import Unsafe


class PubSubManager:
    def _handle_emit(self, data: bytes | Any, *args: Any, **kwargs: Any) -> Unsafe[Any]: ...
    def _handle_callback(self, data: bytes | Any, *args: Any, **kwargs: Any) -> Unsafe[Any]: ...


class RedisManager(PubSubManager): ...
class KombuManager(PubSubManager): ...
class KafkaManager(PubSubManager): ...
class ZmqManager(PubSubManager): ...

