from pathlib import Path
from typing import NewType

TrustedPath = NewType("TrustedPath", Path)
TrustedBytes = NewType("TrustedBytes", bytes)
TrustedArtifact = NewType("TrustedArtifact", Path)

def trusted_path(path: Path, *, reason: str) -> TrustedPath: ...
def verify_path_sha256(path: Path, expected_sha256: str) -> TrustedPath: ...
def trusted_bytes(data: bytes, *, reason: str) -> TrustedBytes: ...
def verify_bytes_sha256(data: bytes, expected_sha256: str) -> TrustedBytes: ...
def trusted_artifact(path: Path, *, reason: str) -> TrustedArtifact: ...
