"""Strict PyYAML stubs — unsafe loaders return Unsafe[Any]."""

from typing import Any

from _unsafe import Unsafe


def load(stream: Any, Loader: Any = ..., *args: Any, **kwargs: Any) -> Unsafe[Any]: ...
def unsafe_load(stream: Any, *args: Any, **kwargs: Any) -> Unsafe[Any]: ...
def full_load(stream: Any, *args: Any, **kwargs: Any) -> Unsafe[Any]: ...
def safe_load(stream: Any, *args: Any, **kwargs: Any) -> Any: ...
