"""Strict marshal stubs — Python object deserialization returns Unsafe[Any]."""

from typing import Any

from _unsafe import Unsafe


def load(file: Any, *args: Any, **kwargs: Any) -> Unsafe[Any]: ...
def loads(bytes: bytes | bytearray | memoryview, *args: Any, **kwargs: Any) -> Unsafe[Any]: ...
def dump(value: Any, file: Any, *args: Any, **kwargs: Any) -> None: ...
def dumps(value: Any, *args: Any, **kwargs: Any) -> bytes: ...
