from typing import Any

from _unsafe import Unsafe


class ShelveStore:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, key: str) -> Unsafe[Any]: ...
    def get(self, key: str, default: Any = ...) -> Unsafe[Any] | Any: ...
    def load(self, key: str, *args: Any, **kwargs: Any) -> Unsafe[Any]: ...

