from typing import Any, TypeVar, overload

from _unsafe import Unsafe

_T = TypeVar("_T")


class ShelveStore:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, key: str) -> Unsafe[Any]: ...
    @overload
    def get(self, key: str) -> Unsafe[Any]: ...
    @overload
    def get(self, key: str, default: _T) -> Unsafe[Any] | _T: ...
    def load(self, key: str, *args: Any, **kwargs: Any) -> Unsafe[Any]: ...
