from typing import Any

from falcon_secure._unsafe import Unsafe
from falcon_secure.trust import TrustedBytes, TrustedPath

def pickle_loads(data: TrustedBytes, *args: Any, **kwargs: Any) -> Unsafe[Any]: ...
def joblib_load(path: TrustedPath, *args: Any, **kwargs: Any) -> Unsafe[Any]: ...
def torch_load(path: TrustedPath, *args: Any, **kwargs: Any) -> Unsafe[Any]: ...
